---
- hosts: 172.31.28.243
  become: yes
  tasks:

  - name: create a folder
    file:
    path: /home/loli/MyAsible/myfolder
    state: directory

  - name: create the file
    file:
      path: /home/loli/MyAsible/myfolder/myfirstfile
      state: touch