---
- hosts: 172.31.28.243
  become: yes
  tasks:

  - name: create a folder
    file:
      path: /home/loli/MyAnsible/myfolder
      state: directory

  - include_tasks: myfile.yml
  - name: copy the file into node 01
    copy:
      src: mytextfile
      dest: /home/loli/MyAnsible

  - name: copy the file from net 
    get_url:
       src: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.10/bin/apache-tomcat-10.0.10.tar.gz
       dest: /home/loli/MyAnsible/apache-tomcat-10.0.10.tar.gz
       force_basic_outh: yes

  - name: need to install apache2 web server
    apt: 
      name: apache2 
      state: present

  - name: change the index file in node01
    template:
      src: myindex.j2
      dest: /var/www/html/index.html