---
- hosts: 172.31.28.243
  become: yes
  tasks:

  - name: create a folder
    file:
      path: /home/loli/MyAnsible/myfolder
      state: directory

  - include_tasks: myfile.yml
  - name: copy the file into node 01
    copy:
      src: mytextfile
      dest: /home/loli/MyAnsible