---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: install apache2 server  
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: I need to install httpd server on redhat
    dnf:
      name: httpd
      state: present
    when: ansible_os_family=="ReadHat" 

  - name: I need to start http service
    service: 
      name: httpd
      state: started
    when: ansible_os_family=="ReadHat"