---
- hosts: mywebservers
  become: yes
  gather_facts: yes

  tasks:
  - name: install apache2 server  
    apt:
      name: "{{mywebpackonubantu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start apache2 service
    service:
      name: "{{mywebpackonubantu}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: I need to install httpd server on redhat
    dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat" 

  - name: I need to start http service
    service: 
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="RedHat"