---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: install apache2 server  
    apt:
      name: apache2
      state: present

  - name: i want to start apache2 service
    service:
      name: apache2
      state: started
      
  