---
- name: create link files tomcat up
  command:
    cmd: ln -s /opt/tomcat-9.0.55/bin/startup.sh /usr/local/bin/tomcatup
    creates: /opt/tomcat/LICENSE
    
- name: create link files tomcat down
  command:
    cmd: ln -s /opt/tomcat-9.0.55/bin/shutdown.sh /usr/local/bin/tomcatdown
    creates: /opt/tomcat/LICENSE