---
- name: copy host-manager/META-INF/context.xml file into node side 
  template:
     src: templates/myhostcontext.j2
     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml 

- name: copy manager /META-INF/context.xml file into node side 
  template:
    src: templates/mymangercontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcat user file into ansible node side
  template:
     src: templates/mytomuser.j2
     dest: /opt/tomcat/conf/tomcat-users.xml